---
- hosts: webservers
  
  become: true   #Lanza la tarea como superusuario
  tasks:
        ##
        # Instalacion de paquetes necesarios.
        # #
          - name: General | Instalacion de paquetes requeridos.
            become: true
            apt:
                    name:
                            - python3
                            - vim
                    state: present
         ##
         # Instalacion de docker
         # #
          - name: Anadir Docker GPG key
            apt_key: url=https://download.docker.com/linux/ubuntu/gpg

          - name: Anadir repositorio Docker APT
            apt_repository:
                    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
          - name: Instalacion lista de paquetes Docker
            apt:
                    name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce']
                    state: present
                    update_cache: yes
            tags: docker
         ##
         # Instalacion de docker-compose
         # #
          - name: Instalacion de docker-compose
            get_url:
                    url: https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Linux-x86_64
                    dest: "/home/kevin"
                    mode: 0755 
         ##
         #  Copiar archivo docker-compose en el nodo
         # #
          - name: Copiar archivo creacion pagina web en nodo local
            copy:
                    src: /home/kevin/Descargas/docker-compose.yml
                    dest: /home/kevin/Desktop/SitioWeb01/
        ##
        # Se levanta / ejecuta el servicio paginaWeb-docker-compose.yml 
        # #
          - name: Se levanta la pagina web
            docker_service:
                    project_src: /home/kevin/Desktop/SitioWeb01/
                   
